version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
configuration: Release
platform: x86
environment:
  COVERALLS_REPO_TOKEN:
    secure: w6yF8ULdQfsRMAv7vq3yFZ/d/7ZQSbL0PZUZRHvpszoW5vIDAyQiemXyfcJu6Sp3
before_build:
  - git submodule update --init --recursive
  - git clone https://github.com/andburn/powershell.git C:\projects\build\Powershell
  - ps: .\Scripts\bootstrap.ps1
  - ps: .\Scripts\appveyor.ps1 EndGame -PreBuild
build:
  project: EndGame.sln
  verbosity: minimal
after_build:
- ps: .\Scripts\appveyor.ps1 EndGame -PostBuild
after_test:
- ps: .\Scripts\appveyor.ps1 EndGame -PostTest
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: Update $(APPVEYOR_REPO_TAG_NAME)
  description: Description
  auth_token:
    secure: OpNj+lrWxBC7mLLsC2F7BqFrwrOBXsgqelz6t0wK8pqIBjO7Imn9Adp+k6OuNbCN
  artifact: Release
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
